/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Avaliacao;
import classes.Categoria;
import classes.Controle;
import classes.HistoricoAvaliacao;
import classes.Profissional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiag
 */
public class EditarAvaliacaos extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarAvaliacaos.class.getName());
    Controle controle;
    Avaliacao avaliacao;

    /**
     * Creates new form EditarAvaliacao
     */
    public EditarAvaliacaos(JDialog parent, boolean modal, Controle controle, Avaliacao avaliacao) {
        super(parent, modal);
        this.controle = controle;
        this.avaliacao = avaliacao;
        initComponents();

        cbCategoria.removeAllItems();
        for (classes.Categoria c : controle.getListaCategorias()) {
            cbCategoria.addItem(c.getNome());
        }

        tfdData.setText(avaliacao.getData());
        tfdValor.setText(String.valueOf(avaliacao.getCusto()));
        tfdCodPro2.setText(String.valueOf(avaliacao.getProfissional().getCod()));
        taEntrada.setText(avaliacao.getRelato());

        if (avaliacao.getCategoria() != null) {
            cbCategoria.setSelectedItem(avaliacao.getCategoria().getNome());
        }
        if (avaliacao.getNome() != null) {
            cbNomeAval.setSelectedItem(avaliacao.getNome());
        }

        setLocationRelativeTo(parent);
    }

    private void adicionarCategorias() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Categoria c : controle.getListaCategorias()) {
            model.addElement(c.getNome());
        }
        cbCategoria.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbNomeAval = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfdData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEntrada = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        tfdCodPro2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOME AVALIAÇÃO:");

        cbNomeAval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antropometria", "Anamnese", "Bioimpedância", "Teste de força" }));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DATA:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("VALOR: R$");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CODÍGO PROFISSIONAL:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CATEGORIA:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("OBSERVAÇÕES:");

        taEntrada.setColumns(20);
        taEntrada.setRows(5);
        jScrollPane1.setViewportView(taEntrada);

        btnCancelar.setBackground(new java.awt.Color(242, 68, 68));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvar.setBackground(new java.awt.Color(39, 200, 108));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdValor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdCodPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdCodPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (tfdData.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe uma data!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (tfdValor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um valor!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (tfdCodPro2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o código do profissional!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // TRAVA DE SEGURANÇA: Evita que getSelectedItem() retorne nulo e estoure o NullPointerException
        if (cbCategoria.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria válida antes de salvar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double custo = Double.parseDouble(tfdValor.getText().trim());
            int codProf = Integer.parseInt(tfdCodPro2.getText().trim());

            Profissional profAux = controle.buscarProfissional(codProf);
            if (profAux == null) {
                JOptionPane.showMessageDialog(this, "Profissional não encontrado com o código informado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String catSelecionada = cbCategoria.getSelectedItem().toString();
            classes.Categoria catAux = null;
            for (classes.Categoria c : controle.getListaCategorias()) {
                if (c.getNome().equalsIgnoreCase(catSelecionada)) {
                    catAux = c;
                    break;
                }
            }

            if (catAux == null) {
                JOptionPane.showMessageDialog(this, "Categoria selecionada não é válida no sistema!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            avaliacao.setNome(cbNomeAval.getSelectedItem().toString());
            avaliacao.setData(tfdData.getText().trim());
            avaliacao.setCusto(custo);
            avaliacao.setRelato(taEntrada.getText().trim());
            avaliacao.setProfissional(profAux);
            avaliacao.setCategoria(catAux);

            JOptionPane.showMessageDialog(this, "Avaliação editada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Os campos de Valor e Código do Profissional devem conter apenas números!", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbNomeAval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taEntrada;
    private javax.swing.JTextField tfdCodPro2;
    private javax.swing.JTextField tfdData;
    private javax.swing.JTextField tfdValor;
    // End of variables declaration//GEN-END:variables
}
