/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.Controle;
import classes.Instrutor;
import classes.Coordenador;
import classes.Profissional;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Thiag
 */
public class GerenciarProfissionais extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarProfissionais.class.getName());
    Controle controle;
    /**
     * Creates new form GerenciarProfissionais
     */
    public GerenciarProfissionais(java.awt.Frame parent, boolean modal, Controle controle) {
        super(parent, modal);
        this.controle = controle;
        initComponents();
        
        setLocationRelativeTo(parent);
    }
    
    public void listarProfissionais(){
        ArrayList<Profissional> listaAux = controle.getListaProfissionais();
        taSaida.setText("");
        for (Profissional p : listaAux){
            taSaida.append(p.toString() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCadastrarProfissional = new javax.swing.JButton();
        btnListarProfissionais = new javax.swing.JButton();
        btnEditarProfissional = new javax.swing.JButton();
        btnExcluirProfissional = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdbInstrutor = new javax.swing.JRadioButton();
        rdbCoordenador = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("GerenciarAluno"); // NOI18N

        btnCadastrarProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnCadastrarProfissional.setText("CADASTRAR APROFISSIONAL");
        btnCadastrarProfissional.addActionListener(this::btnCadastrarProfissionalActionPerformed);

        btnListarProfissionais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        btnListarProfissionais.setText("LISTAR PROFISSIONAIS");
        btnListarProfissionais.addActionListener(this::btnListarProfissionaisActionPerformed);

        btnEditarProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditarProfissional.setText("EDITAR CADASTRO");
        btnEditarProfissional.addActionListener(this::btnEditarProfissionalActionPerformed);

        btnExcluirProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnExcluirProfissional.setText("EXCLUIR CADASTRO");
        btnExcluirProfissional.addActionListener(this::btnExcluirProfissionalActionPerformed);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TIPO DE PROFISSIONAL:");

        buttonGroup1.add(rdbInstrutor);
        rdbInstrutor.setForeground(new java.awt.Color(0, 0, 0));
        rdbInstrutor.setSelected(true);
        rdbInstrutor.setText("INSTRUTOR");
        rdbInstrutor.addActionListener(this::rdbInstrutorActionPerformed);

        buttonGroup1.add(rdbCoordenador);
        rdbCoordenador.setForeground(new java.awt.Color(0, 0, 0));
        rdbCoordenador.setText("COORDENADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastrarProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(btnListarProfissionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirProfissional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(rdbCoordenador))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProfissional)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnListarProfissionais)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarProfissional)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProfissional))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rdbInstrutor)
                        .addGap(9, 9, 9)
                        .addComponent(rdbCoordenador)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProfissionalActionPerformed
        if (rdbInstrutor.isSelected()){
            CadastrarInstrutores cadastrarProfissional = new CadastrarInstrutores(this, true, controle);
            cadastrarProfissional.setVisible(true);
        }else{
            CadastrarCoordenadores cadastrarCoordenador = new CadastrarCoordenadores(this, true, controle);
            cadastrarCoordenador.setVisible(true);
        }
    }//GEN-LAST:event_btnCadastrarProfissionalActionPerformed

    private void btnListarProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProfissionaisActionPerformed
        listarProfissionais();
    }//GEN-LAST:event_btnListarProfissionaisActionPerformed

    private void rdbInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbInstrutorActionPerformed

    private void btnExcluirProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProfissionalActionPerformed
        String input = JOptionPane.showInputDialog("Código:");
        
        if (input == null) return;
        
        try{
            int cod = Integer.parseInt(input.trim());
            
            Profissional aux = controle.buscarProfissional(cod);
            
            if (aux == null) {
                throw new IllegalArgumentException("Profissional não encontrado");
            }
            
            String cargo = "";
            if (aux instanceof Instrutor){
                cargo = "Instrutor(a)";
            }else{
                cargo = "Coordenador(a)";
            }
            
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o(a) " + cargo + " " 
                + aux.getNome() + "?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (resposta != JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(this, "Operação cancelada!");
                return;
            }
            
            controle.removerProfissional(cod);
            
            JOptionPane.showMessageDialog(this, "Profissional excluído com sucesso!");
            listarProfissionais();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O código deve contar apenas números!", "Erro de Digitação", JOptionPane.ERROR_MESSAGE);
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirProfissionalActionPerformed

    private void btnEditarProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProfissionalActionPerformed
        String cod = JOptionPane.showInputDialog("Código: ");
        
        if (cod == null) return;
        
        if (cod.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "E necessario um Código para pesquisar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int codigo = Integer.parseInt(cod);
            
            Profissional aux = controle.buscarProfissional(codigo);
            
            if (rdbInstrutor.isSelected()){
                if (aux != null && aux instanceof Instrutor){
                    EditarInstrutores editarInstrutor = new EditarInstrutores(this, true, controle, (Instrutor)aux);
                    editarInstrutor.setVisible(true);
                }
            }else {
                if (aux != null && aux instanceof Coordenador){
                    EditarCoordenadores editarCoordenador = new EditarCoordenadores(this, true, controle, (Coordenador)aux);
                    editarCoordenador.setVisible(true);
                }
            }
        
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Codigo so pode conter numeros.");
        }
    }//GEN-LAST:event_btnEditarProfissionalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProfissional;
    private javax.swing.JButton btnEditarProfissional;
    private javax.swing.JButton btnExcluirProfissional;
    private javax.swing.JButton btnListarProfissionais;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbCoordenador;
    private javax.swing.JRadioButton rdbInstrutor;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
