/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Categoria;
import classes.Controle;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiag
 */
public class GerenciarCategorias extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarCategorias.class.getName());
    Controle controle;

    /**
     * Creates new form GerenciarCategorias
     */
    public GerenciarCategorias(JDialog parent, boolean modal, Controle controle) {
        super(parent, modal);
        this.controle = controle;
        initComponents();

        setLocationRelativeTo(parent);
    }

    public void listarCats() {
        taSaida.setText("");
        for (Categoria c : controle.getListaCategorias()) {
            taSaida.append(c.toString() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovaCat = new javax.swing.JButton();
        btnListarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        btnExcluirCat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("GerenciarAluno"); // NOI18N

        btnNovaCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnNovaCat.setText("NOVA CATEGORIA");
        btnNovaCat.addActionListener(this::btnNovaCatActionPerformed);

        btnListarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        btnListarCat.setText("LISTAR CATEGORIAS");
        btnListarCat.addActionListener(this::btnListarCatActionPerformed);

        btnEditarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditarCat.setText("EDITAR CATEGORIA");
        btnEditarCat.addActionListener(this::btnEditarCatActionPerformed);

        btnExcluirCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnExcluirCat.setText("EXCLUIR CATEGORIA");
        btnExcluirCat.addActionListener(this::btnExcluirCatActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNovaCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovaCat)
                .addGap(18, 18, 18)
                .addComponent(btnListarCat)
                .addGap(18, 18, 18)
                .addComponent(btnEditarCat)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCat)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCatActionPerformed
        CadastrarCategorias cadastrarCat = new CadastrarCategorias(this, true, controle);
        cadastrarCat.setVisible(true);
    }//GEN-LAST:event_btnNovaCatActionPerformed

    private void btnListarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCatActionPerformed
        listarCats();
    }//GEN-LAST:event_btnListarCatActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        String registro = JOptionPane.showInputDialog("Número de registro:");

        if (registro == null) {
            return;
        }

        try {
            int cod = Integer.parseInt(registro);

            Categoria aux = controle.buscarCategoria(cod);

            if (aux == null) {
                JOptionPane.showMessageDialog(this, "Categoria não encontrada!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            EditarCategorias editarCat = new EditarCategorias(this, true, aux);
            editarCat.setVisible(true);

            listarCats();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números!", "Erro de Digitação", JOptionPane.WARNING_MESSAGE);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void btnExcluirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCatActionPerformed
        String input = (JOptionPane.showInputDialog("Código:"));

        if (input == null) {
            return;
        }

        try {
            int cod = Integer.parseInt(input.trim());

            Categoria aux = controle.buscarCategoria(cod);

            if (aux == null) {
                JOptionPane.showMessageDialog(this, "Categoria não encontrada!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir a categoria: " + aux.getNome() + "?",
                    "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (resposta != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Operação cancelada.");
                return;
            }

            controle.removerCategoria(cod);

            JOptionPane.showMessageDialog(this, "Categoria excluido com sucesso");
            listarCats();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números!", "Erro de Digitação", JOptionPane.WARNING_MESSAGE);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirCatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnExcluirCat;
    private javax.swing.JButton btnListarCat;
    private javax.swing.JButton btnNovaCat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
