/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.Aluno;
import classes.Controle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Thiag
 */
public class GerenciarAlunos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarAlunos.class.getName());
    Controle controle;
    /**
     * Creates new form GerenciarAlunos
     */
    public GerenciarAlunos(java.awt.Frame parent, boolean modal, Controle controle) {
        super(parent, modal);
        this.controle = controle;
        initComponents();
        
        setLocationRelativeTo(parent);
    }
    
    public void listarAlunos(){
        taSaidaAluno.setText("");
        ArrayList<Aluno> listaAux = controle.getListaAlunos();
        taSaidaAluno.setText("");
        for (Aluno a : listaAux){
            taSaidaAluno.append(a.toString() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarAluno = new javax.swing.JButton();
        btnListarAlunos = new javax.swing.JButton();
        btnEditarAluno = new javax.swing.JButton();
        btnExcluirAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaidaAluno = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("GerenciarAluno"); // NOI18N

        btnCadastrarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnCadastrarAluno.setText("CADASTRAR ALUNO");
        btnCadastrarAluno.addActionListener(this::btnCadastrarAlunoActionPerformed);

        btnListarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        btnListarAlunos.setText("LISTAR ALUNOS");
        btnListarAlunos.addActionListener(this::btnListarAlunosActionPerformed);

        btnEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditarAluno.setText("EDITAR CADASTRO");
        btnEditarAluno.addActionListener(this::btnEditarAlunoActionPerformed);

        btnExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnExcluirAluno.setText("EXCLUIR CADASTRO");
        btnExcluirAluno.addActionListener(this::btnExcluirAlunoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCadastrarAluno)
                .addGap(18, 18, 18)
                .addComponent(btnListarAlunos)
                .addGap(18, 18, 18)
                .addComponent(btnEditarAluno)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirAluno)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        taSaidaAluno.setColumns(20);
        taSaidaAluno.setRows(5);
        jScrollPane1.setViewportView(taSaidaAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoActionPerformed
        CadastrarAlunos cadastrarAluno = new CadastrarAlunos(this, true, controle);
        cadastrarAluno.setVisible(true);
    }//GEN-LAST:event_btnCadastrarAlunoActionPerformed

    private void btnListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunosActionPerformed
        listarAlunos();
    }//GEN-LAST:event_btnListarAlunosActionPerformed

    private void btnEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlunoActionPerformed
        String cpf = JOptionPane.showInputDialog("CPF:");
        
        if (cpf == null) return;
        
        if (cpf.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "E necessario um CPF para pesquisar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Aluno aux = controle.buscarAluno(cpf);
            
            if (aux == null){
                throw new IllegalArgumentException();
            }
            
            EditarAlunos editarAluno = new EditarAlunos(this, true, controle, aux);
            editarAluno.setVisible(true);
            
            listarAlunos();
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro do Sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarAlunoActionPerformed

    private void btnExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlunoActionPerformed
        String cpf = JOptionPane.showInputDialog("CPF:");
        
        if (cpf == null) return;
        
        if (cpf.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "É necessario informar um CPF!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }else if (cpf.trim().length() < 11){
            JOptionPane.showMessageDialog(this, "CPF precisa ter pelo menos 11 digitos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            Aluno aux = controle.buscarAluno(cpf.trim());
            
            if (aux == null){
                throw new IllegalArgumentException("Aluno não encontrado com o CPF: " + cpf);
            }
            
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o(a) aluno(a) " 
                    + aux.getNome() + "?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (resposta != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Operação cancelada.");
                return;
            }
            
            controle.removerAluno(cpf.trim());
            
            JOptionPane.showMessageDialog(this, "Aluno excluido com sucesso!");
            listarAlunos();
            
        } catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExcluirAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnEditarAluno;
    private javax.swing.JButton btnExcluirAluno;
    private javax.swing.JButton btnListarAlunos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaidaAluno;
    // End of variables declaration//GEN-END:variables
}
