/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;
import classes.Controle;
import classes.Convenio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Thiag
 */
public class GerenciarConvenios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarConvenios.class.getName());
    Controle controle;
    /**
     * Creates new form GerenciarConvenios
     */
    public GerenciarConvenios(java.awt.Frame parent, boolean modal, Controle controle) {
        super(parent, modal);
        this.controle = controle;
        initComponents();
        
        setLocationRelativeTo(parent);
    }
    
    public void listarConvenios(){
        ArrayList<Convenio> listaAux = controle.getListaConvenios();
        taSaida.setText("");
        for (Convenio c : listaAux){
            taSaida.append(c.toString() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarConvenio = new javax.swing.JButton();
        btnListarConvenios = new javax.swing.JButton();
        btnEditarConvenio = new javax.swing.JButton();
        btnExcluirConvenio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("GerenciarAluno"); // NOI18N

        btnCadastrarConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnCadastrarConvenio.setText("CADASTRAR CONVÊNIO");
        btnCadastrarConvenio.addActionListener(this::btnCadastrarConvenioActionPerformed);

        btnListarConvenios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        btnListarConvenios.setText("LISTAR CONVÊNIOS");
        btnListarConvenios.addActionListener(this::btnListarConveniosActionPerformed);

        btnEditarConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditarConvenio.setText("EDITAR CONVÊNIO");
        btnEditarConvenio.addActionListener(this::btnEditarConvenioActionPerformed);

        btnExcluirConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnExcluirConvenio.setText("EXCLUIR CONVÊNIO");
        btnExcluirConvenio.addActionListener(this::btnExcluirConvenioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastrarConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(btnListarConvenios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCadastrarConvenio)
                .addGap(18, 18, 18)
                .addComponent(btnListarConvenios)
                .addGap(18, 18, 18)
                .addComponent(btnEditarConvenio)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirConvenio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConvenioActionPerformed
        CadastrarConvenios cadastrarConvenio = new CadastrarConvenios(this, true, controle);
        cadastrarConvenio.setVisible(true);
    }//GEN-LAST:event_btnCadastrarConvenioActionPerformed

    private void btnListarConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarConveniosActionPerformed
        listarConvenios();
    }//GEN-LAST:event_btnListarConveniosActionPerformed

    private void btnExcluirConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirConvenioActionPerformed
        String input = (JOptionPane.showInputDialog("Código:"));
        
        if (input == null) return;
        
        try{
            int cod = Integer.parseInt(input.trim());
            
            Convenio aux = controle.buscarConvenio(cod);
            
            if (aux == null){
                throw new IllegalArgumentException("Convênio não encontrado!");
            }
            
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o convênio: " + aux.getNomeConvenio() + "?", 
                "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (resposta != JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(this, "Operação cancelada.");
                return;
            }
            
            controle.removerConvenio(cod);
            
            JOptionPane.showMessageDialog(this, "Convênio excluido com sucesso");
            listarConvenios();
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números!", "Erro de Digitação", JOptionPane.ERROR_MESSAGE);
            
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirConvenioActionPerformed

    private void btnEditarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConvenioActionPerformed
        String registro = JOptionPane.showInputDialog("Número de registro:");
        
        if (registro == null) return;
        
        try {
            int numRegistro = Integer.parseInt(registro.trim());
            
            Convenio convenio = controle.buscarConvenio(numRegistro);
            
             if (convenio == null){
                 throw new IllegalArgumentException();
             }
             
             EditarConvenios editarConvenio = new EditarConvenios(this, true, controle, convenio);
             editarConvenio.setVisible(true);
             
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "Convênio não encontrado!", "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarConvenioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarConvenio;
    private javax.swing.JButton btnEditarConvenio;
    private javax.swing.JButton btnExcluirConvenio;
    private javax.swing.JButton btnListarConvenios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
