/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Aluno;
import classes.Avaliacao;
import classes.Controle;
import classes.HistoricoAvaliacao;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiag
 */
public class GerenciarHistoricos extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarHistoricos.class.getName());
    Controle controle;
    HistoricoAvaliacao historicoAux = null;

    /**
     * Creates new form GerenciarHistorico
     */
    public GerenciarHistoricos(JDialog parent, boolean modal, Controle controle) {
        super(parent, modal);
        this.controle = controle;
        initComponents();

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdCpf = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        rdbHistCom = new javax.swing.JRadioButton();
        rdbAval = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CPF DO ALUNO:");

        tfdCpf.addActionListener(this::tfdCpfActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifying-glass.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        buttonGroup1.add(rdbHistCom);
        rdbHistCom.setForeground(new java.awt.Color(0, 0, 0));
        rdbHistCom.setText("HISTÓRICO COMPLETO");
        rdbHistCom.addActionListener(this::rdbHistComActionPerformed);

        buttonGroup1.add(rdbAval);
        rdbAval.setForeground(new java.awt.Color(0, 0, 0));
        rdbAval.setSelected(true);
        rdbAval.setText("AVALIAÇÕES");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BUSCAR POR:");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditar.setText("EDITAR AVALIAÇÃO");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(184, 184, 184))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdbAval, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdbHistCom))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnEditar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbAval)
                            .addComponent(rdbHistCom)))
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(41, 41, 41))
        );

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCpfActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (tfdCpf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o CPF para busca!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (tfdCpf.getText().trim().length() < 11 || tfdCpf.getText().trim().length() > 11) {
            JOptionPane.showMessageDialog(this, "CPF invalido, deve ter 11 digitos!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Aluno aluno = controle.buscarAluno(tfdCpf.getText().trim());
        if (aluno == null) {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        historicoAux = controle.buscarHistoricoCpf(tfdCpf.getText().trim());

        if (historicoAux == null) {
            JOptionPane.showMessageDialog(this, "Aluno(a) " + aluno.getNome() + ", não possui histórico cadastrado!");
        } else {
            if (rdbAval.isSelected()) {
                taSaida.setText(historicoAux.retornarTodasAvaliacoes());
            } else {
                taSaida.setText(historicoAux.retornarHistoricoAvaliacaoCompleto());
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rdbHistComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHistComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbHistComActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tfdCpf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "É preciso fazer a busca do histórico primeiro!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (this.historicoAux == null) {
            JOptionPane.showMessageDialog(this, "Nenhum histórico foi encontrado para este aluno! Busque um CPF válido primeiro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (this.historicoAux.getListaAvaliacoes().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Este aluno não possui avaliações registradas para editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int cod = Integer.parseInt(JOptionPane.showInputDialog("Código da Avaliação:"));

            Avaliacao avaliacaoAux = historicoAux.buscarAvaliacaoCod(cod);

            if (avaliacaoAux == null) {
                JOptionPane.showMessageDialog(this, "Avaliação não encontrada!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            EditarAvaliacaos editarAvaliacao = new EditarAvaliacaos(this, true, controle, avaliacaoAux, historicoAux);
            editarAvaliacao.setVisible(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Codígo so pode conter números!", "Aviso", JOptionPane.WARNING_MESSAGE);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbAval;
    private javax.swing.JRadioButton rdbHistCom;
    private javax.swing.JTextArea taSaida;
    private javax.swing.JTextField tfdCpf;
    // End of variables declaration//GEN-END:variables
}
